name: container image
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ko-build/setup-ko@v0.6
      - run: |
          ko build --bare --tags latest --push ./cmd/netbox2dns
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
